### ISSUE TITLE
[BUG] Page.goto chrome-aws-lambda timeout ERR_TIMED_OUT

### ISSUE THREAD

**Issue by sathiyagopal2020** [alixaxel/chrome-aws-lambda#117] opened 2020-04-05 13:29 UTC
## Environment
* `chrome-aws-lambda` Version: 2.1.1
* `puppeteer` / `puppeteer-core` Version: 2.1.1
* OS:
* Node.js Version: 12.x
* Lambda / GCF Runtime:  Nodesjs 12.x

## Expected Behavior

Page.Goto need to work and  need to get response
## Current Behavior

Getting exception with our URL as Timeout

Error: net::ERR_TIMED_OUT at https://ouractualdomain.com/print.html?Req=10&ReqstorID=90165&Key=657104
    at navigate (/var/task/node_modules/puppeteer/lib/FrameManager.js:126:37)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async FrameManager.navigateFrame (/var/task/node_modules/puppeteer/lib/FrameManager.js:96:17)
    at async Frame.goto (/var/task/node_modules/puppeteer/lib/FrameManager.js:414:12)
    at async Page.goto (/var/task/node_modules/puppeteer/lib/Page.js:673:12)
    at async Object.exports.run (/var/task/index.js:121:7)
    at async Runtime.exports.handler (/var/task/index.js:50:5)
  -- ASYNC --
    at Frame.<anonymous> (/var/task/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/var/task/node_modules/puppeteer/lib/Page.js:673:49)
    at Page.<anonymous> (/var/task/node_modules/puppeteer/lib/helper.js:112:23)
    at Object.exports.run (/var/task/index.js:121:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Runtime.exports.handler (/var/task/index.js:50:5)

## Steps to Reproduce

const chromium = require('chrome-aws-lambda');
const puppeteer = require('puppeteer');

 const browser = await chromium.puppeteer.launch({
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
      executablePath: await chromium.executablePath,
      defaultViewport: chromium.defaultViewport,
      args: chromium.args,
      dumpio: true,
   });

let page = await browser.newPage();

// Other logics

await page.goto(	urlValue,{waitUntil: ['networkidle2'] ,timeout: 0}).then (async function (response){
        console.log('Page Printing Entered');
        pdf =await page.pdf({ format: 'A4', printBackground: true });
      });

page.goto chrome-aws-lambda timeout ERR_TIMED_OUT

in Chrome browser the URL able to render within 1.2 seconds but only within in Lambda its timing out.

**Comment by sathiyagopal2020** [comment] 2020-04-05 13:45
Issue happening in this exact line in 

const response = await client.send('Page.navigate', {url, referrer, frameId});

at navigate (/var/task/node_modules/puppeteer/lib/FrameManager.js:126:37)

**Comment by JeevanEashwar** [comment] 2020-04-09 18:06
I came to this repository to raise the same issue. +1 from me.
I get timeout issue for an 'http' URL exactly at "page.goto(url)" line.

**Comment by mgm793** [comment] 2020-05-06 07:26
Same here error, do you know how to solve?

**Comment by alixaxel** [comment] 2020-05-09 00:49
Without the actual URL there's nothing I can do to help.

Closing as invalid, feel free to reopen with a complete repro.

**Closed by alixaxel** 2020-05-09 00:49 UTC
Labels: bug, invalid

**Comment by andre-janino** [comment] 2020-06-15 01:34
This issue reproduces on the following link when running on AWS: https://www.dividaativa.pge.sp.gov.br/sc/pages/crda/emitirCrda.jsf?param=8462

I have no issues whatsoever when running it locally on windows. A few other pages also fail to load.

**Comment by hardikmadhu** [comment] 2020-10-14 18:40
Hi @alixaxel 

I'm facing the same issue.

Here's a URL that's consistently not working : https://www.scraperapi.com/

This is just a test website I'm using to test out my crawler, in no way married to this. The following is my environment / experiment details:

1. AWS Lambda memory - 3008MB and Timeout - 2 Mins.
2. Package.json dependencies
`   "cheerio": "^1.0.0-rc.3",
    "chrome-aws-lambda": "^5.3.1",
    "puppeteer-core": "^5.3.1",
    "redis": "^3.0.2",
    "serverless-offline": "^6.8.0"`
3. Using Serverless to test and deploy.
4. Changed `waitUntil: 'domcontentloaded'`
5. Deploying locally with `sls offline` always works. 

The problem for me however, is more intermittent in nature, and only occurs about 50% of times. 

Please let me know if there's a work around.

Best,
Hardik

**Comment by uriya2** [comment] 2020-11-29 15:25
@alixaxel reproducible with url https://www.ronyohananov.com/

**Comment by YoupKuiper** [comment] 2021-04-15 12:35
I had an issue that looked just like this. For me the problem was solved by taking the lambda outside of my VPC. 

Hope this helps someone.

**Comment by crsurfer** [comment] 2021-05-17 19:45
Same issue here, puppeteer works in my local environment and lambda but without VPC, once I plug this to the VPC its doesn't work and I get the 504 error (regardless of the URL). I need to be in the VPC for the EFS

**Comment by mr-romeijn** [comment] 2021-10-08 14:17
@YoupKuiper @crsurfer You guys managed to find a solution? I'm running into the same problem. When the lambda that implements this package is within a VPC it does not work and gives timeouts (even when using setContent) and not opening remote pages or resources??
