### ISSUE TITLE
[BUG] SSL errors when run in mode with node 10.x env

### ISSUE THREAD

**Issue by gsouf** [alixaxel/chrome-aws-lambda#107] opened 2020-03-04 09:41 UTC
## Environment
* `chrome-aws-lambda` Version: 2.1.1
* `puppeteer` / `puppeteer-core` Version: 2.1.1
* OS: Ubuntu 18.04 
* Node.js Version: 10.19.0
* Lambda / GCF Runtime: GCF

## Expected Behavior

Https page are crawling properly

## Current Behavior

Getting ssl errors. This happens both of locally and on CGF. The same script was working well with traditional puppeteer. 

## Possible Solution

That's also happening on CGF, not related to my machine

## Steps to Reproduce

Take the example from the README:

```
const chromium = require('chrome-aws-lambda');

const main = async () => {
    let result = null;
    let browser = null;

    try {
        browser = await chromium.puppeteer.launch({
            args: chromium.args,
            defaultViewport: chromium.defaultViewport,
            executablePath: await chromium.executablePath,
            headless: chromium.headless,
        });

        let page = await browser.newPage();

        await page.goto('https://example.com');

        result = await page.title();
    } finally {
        if (browser !== null) {
            await browser.close();
        }
    }

    console.log(result);
};

main();
```

- :heavy_check_mark:  run it with node, without specifying env variables. It works well:
```
node test.js
```

- :no_entry_sign:  run it with node, with env AWS_EXECUTION_ENV. It fails with ssl errors:
```
AWS_EXECUTION_ENV=AWS_Lambda_nodejs10.x node test.js
```

**Comment by alixaxel** [comment] 2020-03-04 10:35
@gsouf Seems to be a duplicate of #90 .

**Comment by gsouf** [comment] 2020-03-04 10:38
@alixaxel indeed looks like it's the same. I worked around by setting the env variable to be `AWS_EXECUTION_ENV=AWS_Lambda_nodejs8.10`. So there is something odd going on with it

Note: we cannot afford ignoring SSL errors as you suggested in the other ticket.

**Comment by gsouf** [comment] 2020-03-04 10:50
Most likely related to one of those:

- https://github.com/alixaxel/chrome-aws-lambda/blob/ba8cde3f992fc387ede9b047afee9a4f3eb5ca5c/source/index.js#L7
- https://github.com/alixaxel/chrome-aws-lambda/blob/ba8cde3f992fc387ede9b047afee9a4f3eb5ca5c/source/index.js#L170

**Comment by tnolet** [comment] 2020-03-06 13:22
I'm seeing similar behaviour. We are running chrome-lambda 1.19 on Node10x in canary mode on production. For example, this script:

```js
const puppeteer = require("puppeteer");
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto("https://newborn.seha.sa/");
await browser.close();
```
will throw:

```
ERROR - (node:23) UnhandledPromiseRejectionWarning: Error: net::ERR_CERT_AUTHORITY_INVALID at https://newborn.seha.sa/
```

**Comment by alixaxel** [comment] 2020-05-09 00:39
@gsouf Apologies for only now properly following up on this, but didn't manage to find the time before.

After reading your question more closely I realized that you're actually running on GCP! :sweat_smile: 
The lines you mentioned overlay the new AWS Lambda 2 environment with missing fonts and shared libraries from the [Chromium sysroot](https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/3c248ba4290a5ad07085b7af07e6785bf1ae5b66/debian_stretch_amd64_sysroot.tar.xz), but they should only be executed on AWS Lambda, and not GCP.

So simply **not** setting the `AWS_EXECUTION_ENV` should make your problem go away. :slightly_smiling_face: 

---

@tnolet The underlying cause is [libnss error code 8179](https://www-archive.mozilla.org/projects/security/pki/nss/ref/ssl/sslerr.html#1037319):

```
CERT_PKIXVerifyCert failed err=-8179
```

![image](https://user-images.githubusercontent.com/262782/81458799-4b231880-9194-11ea-9ff7-30ef29c8ecc8.png)

As you can see the certificate chain is incomplete, if you test with cURL you can see that it also fails:

```
$ curl -v https://newborn.seha.sa/
*   Trying 95.177.221.251:443...
* Connected to newborn.seha.sa (95.177.221.251) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /var/cache/ca-certs/anchors
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

However https://www.seha.sa/account/login (after the redirect) works fine.

---

Same thing for the issue reported in #90:

```
$ curl -v https://portal.incometaxindiaefiling.gov.in/e-Filing/UserLogin/LoginHome.html?lang=eng
*   Trying 115.114.126.193:443...
* Connected to portal.incometaxindiaefiling.gov.in (115.114.126.193) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /var/cache/ca-certs/anchors
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

And https://www.incometaxindiaefiling.gov.in/home (before the redirect) works fine.

---

I don't understand why rolling back to Node 8 solves the issue for you (and I can no longer spin up Node 8 Lambdas) but it could be that either Node or Chromium are more lax about the certificates (unlikely) or that the provisioned libnss ships with additional certificates in the system CA cert DB (more likely).

Either way, I'd recommend to upgrade and set `ignoreHTTPSErrors: true` in this case.

**Closed** 2020-05-09 02:27 UTC
Labels: bug
