### ISSUE TITLE
[BUG] locale resources are not loaded

### ISSUE THREAD

**Issue by adamdama** [alixaxel/chrome-aws-lambda#85] opened 2019-12-12 17:15 UTC
We have had good success using this project as a Layer for our lambdas and using chrome to take screenshots of webpages. For the most part everything works well but for some pages I get the following output in the log a lot:
```
[1212/161955.239475:WARNING:resource_bundle.cc(1048)] locale resources are not loaded
[1212/161955.239507:WARNING:resource_bundle.cc(1048)] locale resources are not loaded
[1212/161955.298597:WARNING:resource_bundle.cc(1048)] locale resources are not loaded
[1212/161955.298633:WARNING:resource_bundle.cc(1048)] locale resources are not loaded
```

I tried looking around online and can't seem to find out what the issue is other than chromium is struggling to find locale files. Do you have any idea what is going wrong here?

## Environment
* `chrome-aws-lambda` Version:2.0.1
* `puppeteer` / `puppeteer-core` Version:2.0.0
* OS:Amazon Linux 2
* Node.js Version:10.x
* Lambda / GCF Runtime:Node

## Expected Behavior
Chromium to find locale files in bundled binary

## Current Behavior
Chromium does not find locale resources

**Comment by adamdama** [comment] 2019-12-13 14:41
Upon further investigation it appears this only happens when a video tag is present in the HTML or there is one added via JS.

**Comment by alixaxel** [comment] 2020-01-03 14:20
@adamdama I'm aware of this warning (it's just that), to me it happens every time after a cold boot. It doesn't seem to affect normal behavior tho (locale probably falls back to POSIX) and to make it go away would require the locales to be bundled (which would increase the size and decrease performance).

Closing this as not a bug until there's a pressing need to do so. :wink:

**Closed by alixaxel** 2020-01-03 14:20 UTC
Labels: question

**Comment by whoisjuan** [comment] 2020-10-13 02:27
I think this warning can cause a memory problem that crashes Chromium. I'm trying to debug a crashing browser on a page with a long viewport and this warning gets printed hundreds of times, then I see this: `Out of memory. size=262144`

I presume that there's a process related to this that hogs the memory and causes the crash.

**Comment by noii98** [comment] 2020-12-08 09:03
I'm not able to access DOM after these warnings.
