### ISSUE TITLE
Blank Pdf

### ISSUE THREAD

**Issue by tonyschollum** [alixaxel/chrome-aws-lambda#14] opened 2019-01-14 03:17 UTC
When attempting to capture a PDF using AWS lambda it is always coming back blank.
I have tried going to a url (page.goto) and also simply setting content (page.setContent).
I have also tried with and without: await page.emulateMedia('screen');

I can return the content of the page (page.content) but not create a PDF.

I am using nodejs8.10 runtime
Below is the code I am using and I have also attached the PDF returned, right now I am returning the PDF, later I will save this to S3 instead. 

Any help would be greatly appreciated, thanks a lot

```
// index.js
const serverless = require('serverless-http');
const express = require('express');
const chromium = require('chrome-aws-lambda');
const puppeteer = require('puppeteer-core');
const app = express();

const main = async() => {
    const browser = await puppeteer.launch({
        args: chromium.args,
        defaultViewport: chromium.defaultViewport,
        executablePath: await chromium.executablePath,
        headless: true
    });

    const page = await browser.newPage();
    await page.goto('https://example.com', {waitUntil: 'networkidle2'});
    await page.emulateMedia('screen');
    const pdf = await page.pdf({format: 'A4', footerTemplate: '<div style="font-size:20px;">footer</div>'});
    // close page?
    return pdf;
};

app.get('/', function (req, res) {
    res.send('Hello World!');
});

app.post('/pdf', async function(req, res) {
    const pdf = await main();
    res.contentType("application/pdf");
    res.send(pdf);
});

module.exports.handler = serverless(app);
```

[response.pdf](https://github.com/alixaxel/chrome-aws-lambda/files/2753939/response.pdf)

**Comment by hisham** [comment] 2019-02-06 18:55
+1. PDFs seem to be always blank.

**Comment by alixaxel** [comment] 2019-02-09 18:53
@tonyschollum Which version of `chrome-aws-lambda` / `puppeteer` are you using?

**Comment by tonyschollum** [comment] 2019-02-10 19:38
> @tonyschollum Which version of `chrome-aws-lambda` / `puppeteer` are you using?

Hi @alixaxel 

I was using:
chrome-aws-lambda@1.11.2
puppeteer-core@1.11.0

Cheers

**Comment by vinaymavi** [comment] 2019-02-27 10:16
can we have fix and work around of this issue?

**Comment by alixaxel** [comment] 2019-03-02 17:50
@tonyschollum I seem to be able to generate a non-blank PDF (at least with latest version): [response.pdf](https://github.com/alixaxel/chrome-aws-lambda/files/2922362/response.pdf).

Could you please try again with the latest version and tell me if that solves it?

**Comment by tonyschollum** [comment] 2019-03-11 19:56
Hi @alixaxel,

I have updated but still seem to be getting back blank PDF's.

Now running:
chrome-aws-lambda@1.13.0
puppeteer-core@1.13.0

I have attached the simple example index.js I am testing with if there is anything in there you can see I am doing wrong? I am also deploying this using serverless from a windows machine if that impacts at all.

[index.zip](https://github.com/alixaxel/chrome-aws-lambda/files/2953957/index.zip)

Cheers

**Comment by mitchgillin** [comment] 2019-03-18 18:29
+1 still encountering this. Has anyone found a fix?

**Comment by batman9494** [comment] 2019-03-25 21:27
I had the same issue and felt like I tried everything. As @mitchgillin said there is a good chance the issue is the API Gateway configuration and not this library.

I am using the following code to create the lambda server : 

```
'use strict'
const awsServerlessExpress = require('aws-serverless-express')
const app = require('./index')
const binaryMimeTypes = [
	'application/octet-stream',
	'font/eot',
	'font/opentype',
	'font/otf',
	'image/jpeg',
	'image/png',
	'image/svg+xml',
	'application/pdf' // => This was missing
]
const server = awsServerlessExpress.createServer(app, null, binaryMimeTypes);
exports.handler = (event, context) => awsServerlessExpress.proxy(server, event, context)
```
Also you can configure API gateway by adding `*/*` to the binary types 
![image](https://user-images.githubusercontent.com/15963543/54955267-17b00b00-4f4d-11e9-94f3-e602a28993aa.png)

@tonyschollum I am pretty sure that's your issue, the rest of my code was very much like yours.

**Comment by hisham** [comment] 2019-03-25 21:36
In my case, I am converting the outputted pdf file to base64 and sending it to the client as text (for various reasons). So I don't see how it is an API gateway issue. But I'll have to retest again. https://github.com/Kikobeats/aws-lambda-chrome was working fine for me in existing setup.

**Comment by alixaxel** [comment] 2019-03-26 00:00
@hisham The binary from `Kikobeats/aws-lambda-chrome` was exactly the same that is available on this project (I used to provide the compiled binary on the puppeteer Slack channel). @tonyschollum Can you cook up a minimal example that consistently reproduces the problem you're facing? You have a bunch of dependencies that are unrelated to this project, and setting that all up is very time-consuming.

**Comment by hisham** [comment] 2019-03-26 15:57
@alixaxel - sorry small clarification, the latest Kiko binary did not work for me. I had to revert to an older version of the binary. This is what I'm running currently: 

```
  "dependencies": {
    "@browserless/aws-lambda-chrome": "~1.10.0",
    "browserless": "~4.1.3",
    "puppeteer": "^1.10.0"
  }
```

**Comment by alixaxel** [comment] 2019-03-26 16:23
@hisham `@browserless/aws-lambda-chrome@1.10.0` binary also came from this project.

I'm not sure why you have `browserless` there, but I can only provide support for this project.

Also, I managed to correctly get a PDF and shared it in [my previous comment](https://github.com/alixaxel/chrome-aws-lambda/issues/14#issuecomment-462069700). Please provide a minimal example where I can reproduce this problem, otherwise I'm afraid I cannot offer any kind of support for this.

**Comment by tonyschollum** [comment] 2019-03-26 20:20
Hi @alixaxel 

Attached is a zip of the simple example I was trying but getting blank PDFs.

[chrome-aws-lambda.zip](https://github.com/alixaxel/chrome-aws-lambda/files/3010147/chrome-aws-lambda.zip)

**Comment by alixaxel** [comment] 2019-03-26 22:14
@tonyschollum The reason you are getting a blank PDF is due to API Gateway misconfiguration.

I suggest you look into Swagger to describe your resources and Content-Types, or upload your file to S3.

Following @batman9494 instructions on https://github.com/alixaxel/chrome-aws-lambda/issues/14#issuecomment-476384301 might do the trick as well.

Here's a the output I got: [google.pdf](https://github.com/alixaxel/chrome-aws-lambda/files/3010620/google.pdf).

---

Closing this as a invalid question (since it pertains to AWS Gateway).

**Closed by alixaxel** 2019-03-26 22:14 UTC

**Comment by charmpitz** [comment] 2019-11-04 15:28
I hardly disagree. It should work with `serverless offline start` that has no relation with the API Gateway and still doesn't work.

**Comment by alixaxel** [comment] 2019-11-04 15:58
@charmpitz I'd be happy to reopen this if you share a full repro.

**Comment by Dammmien** [comment] 2019-11-26 14:44
Same issue on my side, except I use `page.setContent()` instead of `page.goTo()`.
Not related to API Gateway, I upload the PDF to S3.

```js
const chromium = require('chrome-aws-lambda');

module.exports = class PDFGenerator {

  async generate(content, path) {
    const executablePath = await chromium.executablePath;
    const browser = await chromium.puppeteer.launch({
      args: chromium.args,
      executablePath,
      defaultViewport: chromium.defaultViewport,
      headless: chromium.headless,
    });
    const page = await browser.newPage();
    await page.setContent(content);
    await page.pdf({ path, format: 'A4' });
    await browser.close();
  }

}
```

**Comment by dcworldwide** [comment] 2020-01-26 03:43
Installed latest today, running `serverless offline start` and I always get a blank PDF

```
app.get('/toPdf', async (req, res, next) => {

    // let result = null;
    let browser = null;

    try {

        browser = await chromium.puppeteer.launch({
            args: chromium.args,
            defaultViewport: chromium.defaultViewport,
            executablePath: await chromium.executablePath,
            headless: true // chromium.headless,
        });

        const page = await browser.newPage()

        let url = undefined // "https://google.com"
        let html = "<h1>dfasdfA</h1>"

        /**
         * networkidle0 - wait until there are 0 network connections for at least 500 ms.
         */
        if (url) {
            await page.goto(url, {
                waitUntil: 'networkidle0',
                timeout: 60 * 1000
            })
        } else {
            await page.setContent(html, {
                waitUntil: 'networkidle0',
                timeout: 60 * 1000
            })
        }

        // await page.addStyleTag({ content: '.nav { display: none} .navbar { border: 0px} #print-button {display: none}' })

        const pdf = await page.pdf({
            format: 'A4',
            displayHeaderFooter: false,
            printBackground: true
        })

        await browser.close()

        let filename = encodeURIComponent("temp.pdf");
        // Ideally this should strip them

        res.setHeader('Content-disposition', 'inline; filename="' + filename + '"')
        res.setHeader('Content-type', 'application/pdf')
        res.setHeader('Content-length', pdf.length)
        // res.set({
        //     'Content-Type': 'application/pdf',
        //     'Content-Length': pdf.length,
        //     'Content- disposition': 'inline; filename = "' + filename + '"'
        // })
        res.status(200)
        return res.send(pdf)
        // res.sendStatus(200)

    } catch (error) {
        // console.error(error)
        // return res.json({ error: JSON.stringify(error) })
        res.sendStatus(500)
        // return context.fail(error);
    } finally {
        if (browser !== null) {
            await browser.close();
        }
    }

    // return context.succeed(result);
    // res.json({ result: JSON.stringify(result) })
});


exports.handler = serverless(app);
```

**Comment by dkabyshev** [comment] 2020-05-27 14:43
For anyone struggling, here's a working example (don't forget to enable binary mapping on API Gateway as in https://github.com/alixaxel/chrome-aws-lambda/issues/14#issuecomment-476384301)

```js
const express = require('express')
const app = express()
const chromium = require('chrome-aws-lambda');

app.get('/', async (_, res) => {
  let browser = null;

  try {
    browser = await chromium.puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });
    const page = await browser.newPage()
    await page.setContent(`
      <html>
        <head>
          <title>Test</title>
        </head>
        <body>
          <h1>Testing.</h1>
        </body>
      </html>
    `);

    const buffer = await page.pdf({
      margin: { top: '30px' },
      scale: 0.98,
      format: 'A4',
      printBackground: true,
      headless: true
    })

    // We can directly serve this buffer to the browser.
    // Set the content type so the browser knows how to handle the response.
    res.type('application/pdf')
    res.set('Content-Length', Buffer.byteLength(buffer, 'utf-8'));      

    res.end(buffer)

    await browser.close()
  } catch (error) {
    console.log(error)
    return
  } finally {
    if (browser !== null) {
      await browser.close();
    }
  }
})

const awsServerlessExpress = require('aws-serverless-express')
const binaryMimeTypes = [
	'application/pdf'
]
const server = awsServerlessExpress.createServer(app, null, binaryMimeTypes);
module.exports.handler = (event, context) => awsServerlessExpress.proxy(server, event, context)
```

**Comment by RealSlimMahdi** [comment] 2020-06-24 14:11
> For anyone struggling, here's a working example (don't forget to enable binary mapping on API Gateway as in [#14 (comment)](https://github.com/alixaxel/chrome-aws-lambda/issues/14#issuecomment-476384301))
> 
> ```js
> const express = require('express')
> const app = express()
> const chromium = require('chrome-aws-lambda');
> 
> app.get('/', async (_, res) => {
>   let browser = null;
> 
>   try {
>     browser = await chromium.puppeteer.launch({
>       args: chromium.args,
>       defaultViewport: chromium.defaultViewport,
>       executablePath: await chromium.executablePath,
>       headless: chromium.headless,
>       ignoreHTTPSErrors: true,
>     });
>     const page = await browser.newPage()
>     await page.setContent(`
>       <html>
>         <head>
>           <title>Test</title>
>         </head>
>         <body>
>           <h1>Testing.</h1>
>         </body>
>       </html>
>     `);
> 
>     const buffer = await page.pdf({
>       margin: { top: '30px' },
>       scale: 0.98,
>       format: 'A4',
>       printBackground: true,
>       headless: true
>     })
> 
>     // We can directly serve this buffer to the browser.
>     // Set the content type so the browser knows how to handle the response.
>     res.type('application/pdf')
>     res.set('Content-Length', Buffer.byteLength(buffer, 'utf-8'));      
> 
>     res.end(buffer)
> 
>     await browser.close()
>   } catch (error) {
>     console.log(error)
>     return
>   } finally {
>     if (browser !== null) {
>       await browser.close();
>     }
>   }
> })
> 
> const awsServerlessExpress = require('aws-serverless-express')
> const binaryMimeTypes = [
> 	'application/pdf'
> ]
> const server = awsServerlessExpress.createServer(app, null, binaryMimeTypes);
> module.exports.handler = (event, context) => awsServerlessExpress.proxy(server, event, context)
> ```
I think you have a typo:
res.end = res.send(buffer) ?
