### ISSUE TITLE
Out of memory error on some URL's

### ISSUE THREAD

**Issue by cjroebuck** [alixaxel/chrome-aws-lambda#61] opened 2019-09-16 08:43 UTC
I get the following error from lambda when trying to make multiple screenshots with a device pixel ratio of 2 or more:

[0916/083542.361633:FATAL:memory.cc(22)] Out of memory. size=524288 
Sept 16 08:35:53 Lambda_2663

If I take just one screenshot it’s fine but I’m trying to stitch multiple screenshots together to make a full height screenshot of a website, and get this error after multiple screenshots have been taken. 

I would appreciate any help or advice on how to debug this. Thank you!

**Comment by cjroebuck** [comment] 2019-09-16 08:48
I should add that this error occurs on 3gb lambda.

**Comment by Kikobeats** [comment] 2019-09-19 16:09
Hello, I'm experimenting with the same problem.

Just to confirm, can you share the URL you're trying to screenshot?

**Comment by alixaxel** [comment] 2019-09-19 19:33
@cjroebuck How high is "high"? Without more info (URL, code, etc...) there's little I can do to help.

On your initial comment you shared this:

> [0916/083542.361633:FATAL:memory.cc(22)] Out of memory. size=524288

524288 bytes is exactly 512MiB - are you sure your Lambda function really has 3GB of RAM allocated? Another thing to be aware is that the theoretical maximum resolution of a screenshot that is able to fit in 3GB of memory is roughly 28377x28377 pixels (excluding overheads and actual encoding):

```
3 GiB = sqrt(3221225472 / 4) = 28377.9
512 MiB = sqrt(536870912 / 4) = 11585.2
```

Please share more details.

**Comment by cjroebuck** [comment] 2019-09-20 04:43
Sure, I will get back with more details ASAP.

**Comment by cjroebuck** [comment] 2019-09-22 06:56
As an update, it seems that the issue was caused when running with the flag: —force-device-scale-factor=2.

Removing this flag resolves the issue.

**Comment by cjroebuck** [comment] 2019-10-01 22:29
So the out of memory issue is back and I can re-create it on a certain URL 100% of the time. 

The url is `http://wallpapersafari.com/w/UrvL4y/` and the reason it triggers this issue is most likely because the url loads up a huge image.

Running this same URL on a normal puppeteer in a VM on digital ocean, there are no such issues. I suspect the problem is to do with the --single-process flag again.

It looks like some kind of shared memory resource is being used up because running on a 3gb lambda the max memory usage is reporting as 978MB:

        REPORT RequestId: 17a19e62-329f-403c-88ab-de55029ad31e	Duration: 11138.35 ms	Billed Duration: 11200 ms	Memory Size: 3008 MB	Max Memory Used: 978 MB	Init Duration: 1149.85 ms	

Here is the code to re-create it:

      const chromium = require("chrome-aws-lambda");

      let args = [
        ...chromium.args,
        // below flags are some things i've tried to see if I can figure anything out before coming back here!
        // "--single-process",
        // "--disable-dev-shm-usage",
        // "--disable-webgl",
        // "--media-cache-size=5242880000",
        // "--disk-cache-size=5242880000",
        // "--unlimited-storage",
        // "--no-sandbox",
        // "--use-gl=swiftshader",
        // `--js-flags="--runtime_call_stats --max-old-space-size=1024 
        // --abort-on-uncaught-exception --trace_gc_object_stats
        // --track_gc_object_stats"`,
      ];

      let browserOptions = {
        args,
        executablePath: await chromium.executablePath,
        headless: true,
        dumpio: true,
      };

      console.log("run with options", browserOptions);

      const browser = await chromium.puppeteer.launch(browserOptions);

      const context = await browser.defaultBrowserContext();

      page = await context.newPage();

      await page.goto("http://wallpapersafari.com/w/UrvL4y/", {
        waitUntil: "load",
      });

      console.log("taking screenshot..");

      let buffer = await page.screenshot();
      console.log("took screenshot ok");

Above code fails with log:

    Oct 01 22:03:16 Lambda_266316613429_us-east-1     chrome-lambda-test [1001/    220311.424904:ERROR:validation_errors.cc(76)]     Invalid message:     VALIDATION_ERROR_UNEXPECTED_NULL_POINTER (null     field 1) 
    Oct 01 22:03:16 Lambda_266316613429_us-east-1     chrome-lambda-test [1001/    220311.425004:WARNING:network_service.cc(193)]     Mojo error in NetworkService:Validation failed     for DiscardableSharedMemoryManager     ResponseValidator     [VALIDATION_ERROR_UNEXPECTED_NULL_POINTER (null     field 1)] 
    Oct 01 22:03:16 Lambda_266316613429_us-east-1     chrome-lambda-test [1001/    220311.425296:FATAL:memory.cc(22)] Out of     memory. size=576000000 
    Oct 01 22:03:16 Lambda_266316613429_us-east-1     chrome-lambda-test #0 0x55877ffccc89 <unknown> 
    ...
    Oct 01 22:03:16 Lambda_266316613429_us-east-1     chrome-lambda-test #17 0x7f871d6d9f1d __clone 
    Oct 01 22:03:16 Lambda_266316613429_us-east-1     chrome-lambda-test - 
    Oct 01 22:03:16 Lambda_266316613429_us-east-1     chrome-lambda-test     Received signal 6 
    Oct 01 22:03:16 Lambda_266316613429_us-east-1     chrome-lambda-test #0 0x55877ffccc89 <unknown> 
    Oct 01 22:03:16 Lambda_266316613429_us-east-1     chrome-lambda-test #1 0x55877ff36e83 <unknown> 
    ....
    Oct 01 22:03:16 Lambda_266316613429_us-east-1     chrome-lambda-test [end of stack trace] 
    Oct 01 22:03:16 Lambda_266316613429_us-east-1     chrome-lambda-test Calling _exit(1). Core file     will not be generated. 
    Oct 01 22:03:16 Lambda_266316613429_us-east-1     chrome-lambda-test 2019-10-01T22:03:11.486Z	    17a19e62-329f-403c-88ab-de55029ad31e	got error     Error: Navigation failed because browser has     disconnected!

**Comment by Kikobeats** [comment] 2019-10-01 22:33
Instead of write into a buffer, pass `path` to the puppeteer to save it into a file.

That worked fine to me

**Comment by cjroebuck** [comment] 2019-10-01 22:56
I should have said that this crashes during navigation. 

It does not get as far as the page.screenshot line so I don’t think it has anything to do with the actual screenshot.

**Comment by cjroebuck** [comment] 2019-10-02 09:17
@Kikobeats I notice that the URL fails on microlink - just sent you a report via email!

**Comment by Kikobeats** [comment] 2019-10-02 10:22
The error under the hood is `Navigation failed because browser has disconnected!` 🤔

**Comment by cjroebuck** [comment] 2019-10-02 10:35
I think that is the top-level error from puppeteer. The 'under the hood' error is due to the chromium process crashing due to being out of memory, hence the browser has 'disconnected'!

**Comment by alixaxel** [comment] 2019-10-02 10:50
@cjroebuck That does indeed seem to be the case, if you skip that huge image it doesn't crash:

```js
const chromium = require('chrome-aws-lambda');

exports.handler = async (event, context) => {
  let result = null;
  let browser = null;

  try {
    browser = await chromium.puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
    });

    let page = await browser.newPage();
    
    await page.setRequestInterception(true);
    
    page.on('request', (interceptedRequest) => {
      if (interceptedRequest.url() === 'https://cdn.wallpapersafari.com/72/72/UrvL4y.jpg') {
        interceptedRequest.abort();
      } else {
        interceptedRequest.continue();
      }
    });

    await page.goto("http://wallpapersafari.com/w/UrvL4y/");

    result = await page.title();
  } catch (error) {
    return context.fail(error);
  } finally {
    if (browser !== null) {
      await browser.close();
    }
  }

  return context.succeed(result);
};
```

Furthermore, only requesting the specific image doesn't seem to crash either:

```js
const chromium = require('chrome-aws-lambda');

exports.handler = async (event, context) => {
  let result = null;
  let browser = null;

  try {
    browser = await chromium.puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
    });

    let page = await browser.newPage();

    await page.goto('https://cdn.wallpapersafari.com/72/72/UrvL4y.jpg');

    result = await page.title();
  } catch (error) {
    return context.fail(error);
  } finally {
    if (browser !== null) {
      await browser.close();
    }
  }

  return context.succeed(result);
};
```

I'm not sure there's an easy fix for this tho, as it's a inherit limitation of the Lambda specs. :/

**Comment by alixaxel** [comment] 2019-10-02 10:55
This is a good hint tho:

```
Oct 01 22:03:16 Lambda_266316613429_us-east-1     chrome-lambda-test [1001/    220311.425296:FATAL:memory.cc(22)] Out of     memory. size=576000000
```

For a 12000x12000 image, 4 bytes per pixel, it's exactly 576000000 bytes.

I need to look into Chromium code to see if there's any way to overwrite the maximum buffer size.

**Comment by cjroebuck** [comment] 2019-10-02 10:58
@alixaxel Thanks for chiming in here. Yep 576mb would be much more than the 512mb /tmp space allowed by the Lambda env - assuming it's writing this to disk somewhere. If it is storing it in RAM, then there should be enough space with 3gb.

**Comment by alixaxel** [comment] 2019-10-02 12:21
@cjroebuck Yeah - unlike GCF, the `/tmp` space is **not** memory mapped, so my guess is that there's a hardcoded threshold that the browser will not exceed under certain (unknown so far) conditions.

I did try to remove the `--memory-pressure-off` flag, but didn't change a thing.

I need more time to look into Chromium source code / flags to see if anything can be done.

**Comment by cjroebuck** [comment] 2019-10-02 13:56
It looks like chromium is writing these large temporary files to /tmp directory. I managed to get the same code working with chrome-aws-lambda on a VM and could see the following files were being written when navigating to the URL, this is after 5 separate navigations, hence the 5 s:

```
$> lsof -s | awk '$5 == "REG"' | sort -n -r -k 7,7 | head -n 50
chromium  24912                   root   79u      REG              252,1 576004096      14608 /tmp/.org.chromium.Chromium.HHssLU (deleted)
chromium  19215                   root   79u      REG              252,1 576004096      14622 /tmp/.org.chromium.Chromium.91YDuK (deleted)
chromium  19011                   root   72u      REG              252,1 576004096       1718 /tmp/.org.chromium.Chromium.yZV48t (deleted)
chromium  14160                   root   76u      REG              252,1 576004096      16467 /tmp/.org.chromium.Chromium.5zCkX3 (deleted)
chromium  10412                   root   77u      REG              252,1 576004096       6897 /tmp/.org.chromium.Chromium.Hflbp1 (deleted)
```

Notice that they are all 576004096 bytes large.

**Comment by Kikobeats** [comment] 2019-10-02 18:06
@alixaxel why the cache size is 32MB?

Could be a aria le value based on machine specs?

**Comment by cjroebuck** [comment] 2019-10-02 19:14
What I don’t understand is 

1. why a 14mb image is generating a 576mb cache entry. 

2. Why requesting the image directly i.e. the cdn link does not cause the same out of memory issue.

I’ve tried disabling cache in puppeteer and using low values for the disk-cache-size and media-cache-size flags and still get this error. I think you’re right that I should now open an issue at pptr or chromium.

Thank you for your help on this.

**Comment by alixaxel** [comment] 2019-10-02 21:32
@Kikobeats This package being specific to AWS Lambda, and Lambda having always 512MB of space on `/tmp` I found out that 32MB is more than enough to satisfy the usual caching needs of a short-lived Lambda and still leave enough room to unpack Chromium and anything else the user might want to.

If it was based on machine specs, we would have to infer the amount of free space in the system, which is not a particularly fast operation. The flag is there, and can be omitted or overridden, but I found it's a good sensible default that provides some speed up in the majority of cases.

**Comment by alixaxel** [comment] 2019-10-02 21:47
@cjroebuck For the first question I have a theory: the 14MB image is actually JPEG-encoded, but to render it the browser has to first "decode" the JPEG into pixels (aka a bitmap) - a bitmap in _browserland_ is usually compressed of four channels (red, green, blue and alpha), each one of those taking a value between 0 and 255, or 8 bits (or 1 byte). In this case, since it's a 12000x12000 pixels image:

```
(12000 * 12000) * 4 = 576000000 bytes
```

The extra 4096 (4KB) you are seeing can likely be explained by some header/padding from Chromium.

As for the second question, I'm not sure either... My guess would be that when you request the image indirectly (thru that page), Chromium considers it an asset and tries to cache it (failing, obviously - why it's not honoring the `*-cache-size` flags is another mystery), but when you are requesting it directly it's no longer consider an asset. That's my best guess at this point.

**Comment by alixaxel** [comment] 2019-10-05 13:23
@cjroebuck If you end up opening an issue with PPTR or Chromium, could you please link it here?

**Closed** 2019-10-13 12:48 UTC
Labels: invalid, wontfix

**Comment by Kikobeats** [comment] 2019-10-15 21:42
@cjroebuck 

I'm moving from AWS Lambda to Kubernetes and looks this URL is now working:
https://api.microlink.io/?url=http%3A%2F%2Fwallpapersafari.com%2Fw%2FUrvL4y%2F&screenshot=

so probably is a thing just related with AWS Lambda or how this library is provisioned 🤔

**Comment by sjl2** [comment] 2020-03-11 21:46
Has anyone else ran into this? We're also seeing the same issues, but are not in a spot to be able to move from Lambda to container-based infrastructure. Is the current suggestion to still open up a ticket with Puppeteer or Chromium?

On an unrelated note, has anyone been able to reproduce this locally in a Docker container? We tried to reproduce locally by limiting the memory and `/tmp` disk space, but neither seemed to reproduce the error.

**Comment by kennyhyun** [comment] 2020-04-21 07:03
I had a similar issue on AWS EC2 instance. and it was fixed after freeing up some disk space on the instance.

**Comment by richarddd** [comment] 2020-05-07 15:27
I have the same issue while trying to create PDFs from the lambdas :/

**Comment by polmann** [comment] 2020-06-24 16:29
Has anyone tried mounting [AWS' EFS on a lambda](https://aws.amazon.com/blogs/aws/new-a-shared-file-system-for-your-lambda-functions/) and configured chromium to use that as its /tmp? I gave it a shot here and it didn't work, but I'm not sure if I configured it 100% correctly.

**Comment by rayrapetyan** [comment] 2020-07-17 16:43
were getting:
> stderr: [0717/163455.681939:FATAL:memory.cc(38)] Out of memory. size=262144

`--single-process` resolved this issue for me

**Comment by whoisjuan** [comment] 2020-10-13 04:32
`--max-decoded-image-size-mb` can potentially solve this problem with a caveat. Have in mind that the more aggressive you go with this setting, the more likely your function will succeed without Chromium running out of memory.

So something like `--max-decoded-image-size-mb=1` could be enough to fix the problem, but here is the caveat. `--max-decoded-image-size-mb` is not a compression algorithm. With this flag is the image will get dropped completely if it goes above a threshold.

I'm not entirely sure what's determines the threshold. It doesn't seem to be the inflated size since I tested this with an aggressive value of `0.2` and many pages seemed to load the images normally without dropping it. But the larger the actual sizes were, the more likely the image would get dropped.

Leaving this as a potential solution here since I know not everyone is screenshotting or screenshotting without a particular strict need for accuracy.

**Comment by vieirai** [comment] 2020-10-27 17:45
> Has anyone tried mounting [AWS' EFS on a lambda](https://aws.amazon.com/blogs/aws/new-a-shared-file-system-for-your-lambda-functions/) and configure chromium to use that as its /tmp? I gave it a shot here and it didn't work, but I'm not sure if I configured it 100% correctly.

As someone who did exactly this and ran it in production for a few months, my advice is **don't do it**.

Chromium writes to the `/tmp` folder when loading images on a page and when taking screenshots. The bigger the images/screenshot the more it writes.

What I found is that EFS's throughput wasn't enough to deal with this much I/O operations when trying to run at scale (you're sharing a single EFS with all of your lambdas). 

In the end we ended just placing the chromium binary in EFS and letting chromium write to `/tmp`, this somewhat worked and allows us to run slightly larger images/screenshots as we've freed 130MB of space, but it's expensive (you need to run EFS in provisioned throughput mode) and it's still limited.

**Comment by ahansson89** [comment] 2022-03-29 23:57
Should be fixed with this https://aws.amazon.com/blogs/aws/aws-lambda-now-supports-up-to-10-gb-ephemeral-storage/
